import assert from 'node:assert/strict';
import {extractFreightAd,getAIStatus} from './ai-runtime.mjs';
process.env.AI_ENABLED='true';delete process.env.OPENAI_API_KEY;
let calls=0;
const result={publish:true,kind:'load',from_city:'حمص',to_city:'العقبة',from_country:'سوريا',to_country:'الأردن',cargo_type:null,vehicle_type:'شاحنة',weight_tons:null,trucks_required:1,confidence:0.95};
const response=(value,finish='stop',refusal=null)=>({ok:true,json:async()=>({choices:[{finish_reason:finish,message:{content:JSON.stringify(value),refusal}}]})});
const fetchImpl=async(url,options)=>{calls++;assert.equal(url,'https://api.openai.com/v1/chat/completions');const body=JSON.parse(options.body);assert.equal(body.response_format.json_schema.strict,true);assert.equal(body.store,false);assert(!('contact_phone' in body.response_format.json_schema.schema.properties));return response(result);};
assert.equal(await extractFreightAd('شاحنة من حمص إلى العقبة',{fetchImpl}),null);assert.equal(calls,0);assert.equal(getAIStatus().status,'not_configured');
const options={apiKey:'test-key-not-real',fetchImpl};
assert.equal(await extractFreightAd('السلام عليكم',options),null);assert.equal(calls,0);
assert.equal((await extractFreightAd('شاحنة من حمص إلى العقبة',options)).kind,'load');assert.equal(calls,1);
await extractFreightAd('شاحنة من حمص إلى العقبة',options);assert.equal(calls,1);
assert.equal(await extractFreightAd('شاحنة خطأ',{...options,fetchImpl:async()=>({ok:false,status:401})}),null);
assert.equal(await extractFreightAd('شاحنة رفض',{...options,fetchImpl:async()=>response(result,'stop','refused')}),null);
assert.equal(await extractFreightAd('شاحنة ناقص',{...options,fetchImpl:async()=>response(result,'length')}),null);
assert.equal(await extractFreightAd('شاحنة انقطاع',{...options,fetchImpl:async()=>{throw Error('timeout')}}),null);
assert.equal(await extractFreightAd('شاحنة خطأ تنسيق',{...options,fetchImpl:async()=>({ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:'invalid JSON'}}]})})}),null);
process.env.AI_ENABLED='false';assert.equal(await extractFreightAd('شاحنة من حمص إلى العقبة',options),null);
console.log('PASS: no-key/disabled gates, schema, cache, authentication failure, refusal, incomplete response and timeout fallback. No live API calls.');
